### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by crossjs** [crossjs/plato#2]
### 基础

- [x] 路由切换显示 progress bar

### 组件

- [x] Image
- [ ] Radio/RadioList
- [x] Password 支持查看密码
- [x] 不再支持双态组件
- [x] 组件更原子化
- [x] 带链接地址的 cell，响应区域修改为整个 cell
- [ ] 优化 checkbox
- [ ] 优化 picker
- [x] 优化 Icon，使用字符别名？
- [x] navibar，自定义 icon？
- [x] action sheet

### 数据

- [x] 缓存与持久化
- [x] ajax as a plugin
- [x] ajax 支持全局配置
- [ ] ajax 支持动态修改全局配置？
- [x] 分离 ajax core

### 表单验证

- [x] 移除 vue-validator？
- [x] 使用更简单的非侵入式验证
- [x] 表单控件初始化后自动验证
- [ ] 支持异步校验
- [ ] 支持自定义校验（使用纯函数？）

### 国际化

- [x] 国际化按需加载
- [x] 优化国际化实现（现在的实现方式太不优雅了）
- [ ] 缓存国际化资源？
- [x] i18n 支持全局配置

### 其它

- [ ] 换肤，支持将皮肤独立，不参与打包
- [ ] 使用 `vuex-router-sync`？
- [x] 增加 history.back 按钮

### 调试工具

- [ ] 移动端日志打印？

**Comment by crossjs** [comment]
all rewrited in 2.x, this issue is outdate

**Comment by lynzz** [comment]
表单验证 https://github.com/yiminghe/async-validator 这个可以参考，适合 vue2.0

**Comment by crossjs** [comment]
@lynzz 异步校验的支持有在考虑中，只是因为目前还没有很强的需求，就暂时放后了。
移动端确实不想过重，目前的原则是：只提供基础能力，同时尽量做成可插拔，让开发者自由选择。
